// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDStmXdQdR7_Mt6Rnlov0Bqrtw1_7VDw2o",
      authDomain: "smarbox-1260b.firebaseapp.com",
      projectId: "smarbox-1260b",
      storageBucket: "smarbox-1260b.appspot.com",
      messagingSenderId: "503763831683",
      appId: "1:503763831683:web:a2e02e87d2b1b1e8a904b6",
      measurementId: "G-QNMNZJ5QKV");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDStmXdQdR7_Mt6Rnlov0Bqrtw1_7VDw2o",
      authDomain: "smarbox-1260b.firebaseapp.com",
      projectId: "smarbox-1260b",
      storageBucket: "smarbox-1260b.appspot.com",
      messagingSenderId: "503763831683",
      appId: "1:503763831683:web:a2e02e87d2b1b1e8a904b6",
      measurementId: "G-QNMNZJ5QKV");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDStmXdQdR7_Mt6Rnlov0Bqrtw1_7VDw2o",
    authDomain: "smarbox-1260b.firebaseapp.com",
    projectId: "smarbox-1260b",
    storageBucket: "smarbox-1260b.appspot.com",
    messagingSenderId: "503763831683",
    appId: "1:337718001929:ios:c8c21e52928b929a7593d8",
    measurementId: "G-QNMNZJ5QKV",
    androidClientId: '',
    iosClientId: '',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyDStmXdQdR7_Mt6Rnlov0Bqrtw1_7VDw2o",
      authDomain: "smarbox-1260b.firebaseapp.com",
      projectId: "smarbox-1260b",
      storageBucket: "smarbox-1260b.appspot.com",
      messagingSenderId: "503763831683",
      appId: "1:503763831683:web:a2e02e87d2b1b1e8a904b6",
      measurementId: "G-QNMNZJ5QKV");
}
